### ISSUE TITLE
Pubchem http/2 problems

### ISSUE THREAD

**Issue by andschar** [ropensci/webchem#172]
Recently I have problems querying the Pubchem API with webchem. I get the following error:

> Error: lexical error: invalid char in json text.
                                       <?xml version="1.0" encoding="U
                     (right here) ------^
> In addition: Warning message:
> In FUN(X[[i]], ...) : Problem with web service encountered... Returning NA.

The problem arises in all Pubchem functions. It is actually not a parsing error of the json data but falls back to an apparently known bug in nginx which is in turn used in the R package curl and therefore in httr::POST(). See discussion [here](https://github.com/jeroen/curl/issues/156). Like in the referenced issue, I'm using the curl library 7.58.0

A workaround is to add `config(http_version = 0)` to the POST request, which tuns off http/2 from the client side (as done [here](https://github.com/ropensci/monkeylearn/pull/15/files)). I have tested it and it works like a charm.

If you're ok with adding this to all the PubChem funcitons, I would be happy to file a PR as soon as we resolve #171 . Correct me if I misunderstood something.

```r
# the error occurs at some point in the query
todo = c("ALEXXDVDDISNDU-JZYPGELDSA-N", "DDBREPKUVSBGFI-UHFFFAOYSA-N", 
"ITRJWOMZKQRYTA-RFZYENFJSA-N", "MECHNRXZTMCUDQ-VLOQVYPSSA-N", 
"NWIBSHFKIJFRCO-WUDYKRTCSA-N", "PJJJBBJSCAKJQF-UHFFFAOYSA-N", 
"SQMCFUSVGSBKFK-UHFFFAOYSA-M", "UREBDLICKHMUKA-CXSFZGCWSA-N", 
"WCNLCIJMFAJCPX-UHFFFAOYSA-N", "WSFSSNUMVMOOMR-UHFFFAOYSA-N")
get_cid(todo, from = 'inchikey', verbose = TRUE)
```

**Comment by EDiLD** [comment]
Yes, saw this curl issue also...
Can you check how it was solved in entrez (@sckott) and implement the same fix here?

I feel that this should be fixed upstream (curl, httr) instead of here.

Eduard

**Comment by sckott** [comment]
this is what david has done in rentrez https://github.com/ropensci/rentrez/blob/5d552d7b5a1a9a0e536cc6f10c6d2305d7eddbd8/R/base.r#L55-L66 

i've had reports from users in other pkgs, but I havent attempted fixes yet. I will probably do something like rentrez does

i'm not sure fixing it at the curl or similar layer is appropriate since those http clients provide methods for doing HTTP requests. servers will vary a lot in whether they use http2 or not and so I think it makes sense at the layer o f pkgs like this one to implement fixes as needed

**Comment by stitam** [comment]
@andschar can your please check if this is still an issue? I could not reproduce it (`curl 7.60.0`).

**Comment by andschar** [comment]
You are right it's not an issue anymore. I ran a query with 14000 requests over night an it worked.
