### ISSUE TITLE
Getting Error in UseMethod("xml_find_first") :    no applicable method for 'xml_find_first' applied to an object of class "try-error"

### ISSUE THREAD

**Issue by moradkhantig** [ropensci/webchem#268]
I'm using the ci_query in the webchem package to query the ChemIDPlus database. Starting from July 2 I've been getting the following error when running the query:

Error in UseMethod("xml_find_first") : 
  no applicable method for 'xml_find_first' applied to an object of class "try-error"

This error is thrown even when I run the example provided in the documentation (https://cran.r-project.org/web/packages/webchem/webchem.pdf) on page 10:

y1 <- ci_query(c('Formaldehyde', 'Triclosan'), type = 'name')

**Comment by marcodilger** [comment]
same as #265 
(does this happen when ChemIDPlus is temporarely not responding?)

**Comment by stitam** [comment]
Thanks for raising the issue @moradkhantig. This error message comes from the `ci_query()` being unable to read the url. This usually happens when the server is not responding (thanks @marcodilger for mentioning that) so I am quite certain the failure is on the webservice's end. I'll update the function to return HTTP status codes so next time we'll have a better clue.

**Comment by stitam** [comment]
Hi @moradkhantig, in order to confirm webservice failures in the future, all functions that query webservices should now print http status messages by default. `ci_query()` seems to be working, so I am closing this issue, but let us know if the error comes back.
