### ISSUE TITLE
no API key stored for ChemSpider

### ISSUE THREAD

**Issue by Ellakai** [ropensci/webchem#370]
Dear you,

I have an issue with your tool.
I would like to use, but each time i obtain this code : no API key stored for ChemSpider

I don't know how i can integrate my API Key :(

Thanks for your help
regards

**Comment by stitam** [comment]
Hi @Ellakai, thanks for raising this issue. Webchem supports two alternatives for using your API key: 1. you can provide your API key at each ChemSpider function call using the `apikey` argument e.g. `cs_convert(160, from = "csid", to = "smiles", apikey = "xyz")` or 2. you can add your API key to your .Renviron file. I personally use option 2 because this way I don't have to copy/paste my API key every time I use ChemSpider, R just remembers it. The help pages for `cs_check_key()` should help you set up your .Renviron file appropriately. Have you managed to get it working?

**Comment by Ellakai** [comment]
Thanks for you replay.

When i add my API key; i have the same error message

[url=https://ibb.co/N16YXGF][img]https://i.ibb.co/7gJyH0S/Capture-d-e-cran-2022-10-04-a-19-35-12.png[/img][/url]

I would like to use this way because i can launch the code on different computeur

(this key is free key for this moment, no problem if i share here)


thanks

**Comment by stitam** [comment]
Thanks @Ellakai I could reproduce your issue, it seem like  bug, I'll look into it.

**Comment by Ellakai** [comment]
Thank you very much :)
I have the same issue on my Laptop (mac) and my computeur (Windows 10).

Thanks again

**Comment by Ellakai** [comment]
Thank you very much :)
I have the same issue on my Laptop (mac) and my computeur (Windows 10).

Thanks again

**Comment by stitam** [comment]
The functions should now work properly in the dev version: `devtools::install_github("https://github.com/ropensci/webchem")`. Does it work on your end @Ellakai ?

**Comment by Ellakai** [comment]
It's seems running :)
perfect

i will integrate in my script tomorrow, but i think it's nice now

thank you very well :)
and thanks for your tool

thanks
regards
