### ISSUE TITLE
`pan_query()` still broken.  Should it be made defunct for v 1.3.0?

### ISSUE THREAD

**Issue by Aariq** [ropensci/webchem#399]
`pan_query()` returns a message that it is broken when used.  I couldn't find an open issue or PR fixing it. Should we just mark it as defunct in the next version (#395)?

**Comment by stitam** [comment]
This is different from ChemIDPlus because the website is still there we just cannot access it. I asked the organisation for clarification. If there is an API we can rewrite the function if there isn't and they prohibit programmatic access then we need to defunct it. Thanks @Aariq, I agree, let's sort this out before v1.3.0.

**Comment by Aariq** [comment]
Ah I remember now.  I couldn't find the issue where we discussed this previously.

**Comment by Aariq** [comment]
Sad to see it go, but I agree

**Comment by stitam** [comment]
Forgot to remove PAN from README.
